import "./globals.css";
import FooterNavBar from "./components/FooterNavBar";
import { Metadata } from "next";
import { Orbitron, Space_Grotesk, Montserrat } from "next/font/google";
import LeftSideBar from "./components/LeftSideBar";
import MobileNav from "./components/MobileNav";

const orbitron = Orbitron({
  variable: "--font-hero",
  subsets: ["latin"],
  weight: ["400", "700", "900"], // Bold weights for hero
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Ermili Mohamed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${spaceGrotesk.variable} ${montserrat.variable} font-sans`}>
        <LeftSideBar />
        <MobileNav />
        {children}
        <FooterNavBar />
      </body>
    </html>
  );
}