import "./globals.css";
import FooterNavBar from "./components/FooterNavBar";
import { Metadata } from "next";
import { Space_Grotesk, Montserrat, Orbitron } from "next/font/google";
import LeftSideBar from "./components/LeftSideBar";
import MobileNav from "./components/MobileNav";
import { ThemeProvider } from "./components/ThemeProvider";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Ermili Mohamed",
  description: "Generated by create next app",
  icons: {
    icon: "/ErMedlogo.png",
    shortcut: "/ErMedlogo.png",
    apple: "/ErMedlogo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.variable} ${montserrat.variable} ${orbitron.variable} font-sans`}>
        <ThemeProvider>
          <LeftSideBar />
          <MobileNav />
          {children}
          <FooterNavBar />
        </ThemeProvider>
      </body>
    </html>
  );
}